### ISSUE TITLE
repo needs description

### ISSUE THREAD

**Issue by thraxil** [appsembler/xblock-free-text-response#4]
Vanta requires all of our repos to have descriptions.

**Comment by OmarIthawi** [comment]
@bryanlandia @thraxil I think this repo should be archived and the DHIS2 should be using the edX fork:

```yml
- name: "git+https://github.com/edx/xblock-free-text-response.git@release/v0.4.0#egg=freetextresponse"
```

The `release/v0.4.0-i18n` was made for Tahoe's i18n needs and no longer needed due to upstream fixes.

**Comment by thraxil** [comment]
As we're approaching our SOC2 audit window, we can't have any repos that don't have descriptions. If this issue hasn't been addressed by Sep 8, this repo will be automatically archived.
